GAME_FIELD_HEIGHT = 4
GAME_FIELD_WIDTH = 4
INVALID_TILE_NUMBER = -1
EMPTY_TILE_NUM = GAME_FIELD_WIDTH * GAME_FIELD_HEIGHT
START_TILE_NUM = 1
END_TILE_NUM = EMPTY_TILE_NUM - 1
SORTED_TILES_ARRAY = list(range(START_TILE_NUM, EMPTY_TILE_NUM + 1))